config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :listings
  resource :dashboard, only: [:show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/listing.rb
class Listing < ApplicationRecord
  has_one_attached :photo
  belongs_to :user
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :user
end

app/models/swap.rb
class Swap < ApplicationRecord
  belongs_to :listing
  belongs_to :offer
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :listings
  has_many :offers
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController

  def show
    @listing = Listing.new
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController

  def index
    @listings = Listing.all
      @markers = @listings.geocoded.map do |flat|
    {
      lat: listing.latitude,
      lng: listing.longitude
    }
  end
  end

  def show
    @listing = Listing.find(params[:id])
  end

  def create
    @listing = Listing.new(listing_params)
    @listing.user_id = current_user.id
    if @listing.save
      redirect_to listings_path
    end
  end

  def destroy
    @listing = Listing.find(params[:id])
    if @listing.destroy
      redirect_to listings_path
    end
  end

  def new
    @listing = Listing.new
  end

  private

  def listing_params
  params.require(:listing).permit(:location, :house_type, :photo, :start_date, :end_date, :pets, :plants, :bedrooms, :guests)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboards/show.html.erb
<h1>Welcome to the dashboard!</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cambio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Arimo&family=DM+Sans:wght@500&display=swap" rel="stylesheet">
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.css" rel="stylesheet">
    <the-script src="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.js"></the-script>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/listings/index.html.erb
<h1> Available swaps </h1>
<h2>You are seeing listings in specified place...</h1>

<ul class="listings">
  <% @listings.each do |listing| %>
    <li class="listing">
      <%= listing.location %> -
      <%= listing.start_date %> -
      <%= listing.end_date%> -
      <%= listing.house_type%> -
      <%= listing.pets%> -
      <%= listing.plants%> -
      <%= listing.bedrooms%> bedrooms -
      <%= listing.guests%> guests
      <%= cl_image_tag listing.photo.key, height: 300, width: 400, crop: :fill %>
      <%= link_to "See more", listing_path(listing)%>
      <%= link_to "Kill it", listing_path(listing),  method: :delete, data: { confirm: "Are you sure you want to delete this list?" } %>
    </li>
  <% end %>
</ul>

<div style="width: 100%; height: 600px;"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>


<%= link_to "Add a new listing", new_listing_path%>

app/views/listings/new.html.erb
<%= simple_form_for(@listing) do |f| %>

  <%= f.input :location %>
  <%= f.input :start_date, input_html: {class: "datepicker"}   %>
  <%= f.input :end_date, input_html: {class: "datepicker"}   %>
  <%= f.input :house_type, :collection => %w[house flat cabin tent boat room]  %>
  <%= f.input :pets, as: :boolean, boolean_style: :inline %>
  <%= f.input :plants, as: :boolean, boolean_style: :inline %>
  <%= f.input :guests, :collection => %w[1 2 3 4 5 6 7 8 9 10]  %>
  <%= f.input :bedrooms, :collection => %w[1 2 3 4 5]  %>
  <%= f.input :photo, as: :file %>
  <%= f.submit %>

<% end %>

app/views/listings/show.html.erb
<h1><%= @listing.location %></h1>
<%= link_to "home", root_path %>

app/views/pages/home.html.erb
<h1>Welcome to Cambio</h1>


<%= link_to "Listings", listings_path %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://cdn0.iconfinder.com/data/icons/real-estate-and-homes-2/85/house_home_swap_exchange-512.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "home", root_path %>
          </li>
          <li class="nav-item">
            <%= link_to "Dashboard", dashboard_path, class: "nav-link" %>
          </li>
          <li>
            <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://indiehoy.com/wp-content/uploads/2019/05/et-el-extraterrestre-1200x773.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
            <%= link_to "sign up", new_user_registration_path %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>